name: React (Vite) CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build React App (Vite)
        run: npm run build

      - name: Run tests
        run: npm run test

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🔑 Configure AWS credentials using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::274822064527:role/prod-test
          aws-region: sa-east-1

      # 🔐 Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 🐳 Build Docker image
      - name: Build Docker image
        run: |
          docker build -t test:latest .

      # 📤 Tag & Push Docker image to ECR (São Paulo)
      - name: Push Docker image to ECR
        run: |
          docker tag test:latest 274822064527.dkr.ecr.sa-east-1.amazonaws.com/test:latest
          docker push 274822064527.dkr.ecr.sa-east-1.amazonaws.com/test:latest
